import * as THREE from 'three';

export const BOSS_TYPES = [
    // První podlaží
    {
        name: "Ohnivý drak",
        translationKey: "fireDragon",
        specialAttacks: ['multiShot', 'aoeBlast'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xff7542, roughness: 0.1, metalness: 0.1 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffa061, emissive: 0xffa061, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0xffa061),
        attackCooldown: 1,
        attackEmmisiveIntensity: 3,
        minHealth: 1000,
        maxHealth: 1500
    },
    {
        name: "Ledový drak",
        translationKey: "iceDragon",
        specialAttacks: ['frostbolt', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x45c1ff, roughness: 0.1, metalness: 0.1 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x5cf7ff, emissive: 0x5cf7ff, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x8af5ff),
        attackCooldown: 1,
        minHealth: 1500,
        maxHealth: 2000
    },
    {
        name: "Zemní drak",
        translationKey: "earthDragon",
        specialAttacks: ['aoeBlast', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x7bd672, roughness: 0.1, metalness: 0.1 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x5cff74, emissive: 0x5cff74, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x5cff74),
        attackCooldown: 1,
        minHealth: 1000,
        maxHealth: 2000
    },
    // Druhé podlaží
    {
        name: "Bouřkový drak",
        translationKey: "stormDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4169e1, roughness: 0.1, metalness: 0.3 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xecff6e, emissive: 0xecff6e, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x636eff),
        attackCooldown: 0.8,
        attackEmmisiveIntensity: 3,
        minHealth: 3000,
        maxHealth: 4500
    },
    {
        name: "Stínový drak",
        translationKey: "shadowDragon",
        specialAttacks: ['frostbolt', 'teleport', 'aoeBlast'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.2 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x8e4a91, emissive: 0x8e4a91, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x8e4a91),
        attackCooldown: 0.8,
        minHealth: 2500,
        maxHealth: 5000
    },
    {
        name: "Krystalový drak",
        translationKey: "crystalDragon",
        specialAttacks: ['multiShot', 'frostbolt', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x1fffff, emissive: 0x1fffff, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x1fffff),
        attackCooldown: 0.8,
        minHealth: 3000,
        maxHealth: 6000
    },
    // Třetí podlaží
    {
        name: "Nebeský drak",
        translationKey: "celestialDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xadd8e6, roughness: 0.1, metalness: 0.5 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 2 }),
        attackColor: new THREE.Color(0xffffff),
        attackCooldown: 0.6,
        minHealth: 5500,
        maxHealth: 9000
    },
    {
        name: "Lávový drak",
        translationKey: "lavaDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8b0000, roughness: 0.1, metalness: 0.3 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff4500, emissive: 0xff4500, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0xff643d),
        attackEmmisiveIntensity: 3,
        attackCooldown: 0.6,
        minHealth: 8000,
        maxHealth: 11000
    },
    {
        name: "Vesmírný drak",
        translationKey: "spaceDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x3b278f, roughness: 0.1, metalness: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffd700, emissive: 0xffd700, emissiveIntensity: 5 }),
        attackColor: new THREE.Color(0xffe34d),
        attackEmmisiveIntensity: 5,
        attackCooldown: 0.6,
        minHealth: 6000,
        maxHealth: 12500
    },
    // Čtvrté podlaží
    {
        name: "Astrální drak",
        translationKey: "astralDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xE6E6FA, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, emissive: 0xFFFFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xd0a1ff),
        attackCooldown: 0.5,
        attackEmmisiveIntensity: 4,
        minHealth: 8000,
        maxHealth: 12000
    },
    {
        name: "Kvantový drak",
        translationKey: "quantumDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, roughness: 0.1, metalness: 0.7, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, emissive: 0x2e7eff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x2e7eff),
        attackCooldown: 0.4,
        attackEmmisiveIntensity: 4,
        minHealth: 10000,
        maxHealth: 15000
    },
    {
        name: "Éterický drak",
        translationKey: "etherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffb5d8, emissive: 0xffb5d8, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffb5d8),
        attackCooldown: 0.3,
        attackEmmisiveIntensity: 4,
        minHealth: 12000,
        maxHealth: 18000
    },
    // Páté podlaží
    {
        name: "Astrální drak",
        translationKey: "astralDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xE6E6FA, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, emissive: 0xFFFFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xd0a1ff),
        attackCooldown: 0.5,
        attackEmmisiveIntensity: 4,
        minHealth: 8000,
        maxHealth: 12000
    },
    {
        name: "Kvantový drak",
        translationKey: "quantumDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, roughness: 0.1, metalness: 0.7, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, emissive: 0x2e7eff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x2e7eff),
        attackCooldown: 0.4,
        attackEmmisiveIntensity: 4,
        minHealth: 10000,
        maxHealth: 15000
    },
    {
        name: "Éterický drak",
        translationKey: "etherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffb5d8, emissive: 0xffb5d8, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffb5d8),
        attackCooldown: 0.3,
        attackEmmisiveIntensity: 4,
        minHealth: 12000,
        maxHealth: 18000
    },
    // Šesté podlaží
    {
        name: "Astrální drak",
        translationKey: "astralDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xE6E6FA, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, emissive: 0xFFFFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xd0a1ff),
        attackCooldown: 0.5,
        attackEmmisiveIntensity: 4,
        minHealth: 8000,
        maxHealth: 12000
    },
    {
        name: "Kvantový drak",
        translationKey: "quantumDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, roughness: 0.1, metalness: 0.7, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, emissive: 0x2e7eff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x2e7eff),
        attackCooldown: 0.4,
        attackEmmisiveIntensity: 4,
        minHealth: 10000,
        maxHealth: 15000
    },
    {
        name: "Éterický drak",
        translationKey: "etherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffb5d8, emissive: 0xffb5d8, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffb5d8),
        attackCooldown: 0.3,
        attackEmmisiveIntensity: 4,
        minHealth: 12000,
        maxHealth: 18000
    },
    //Sedmé podlaží
    {
        name: "Astrální drak",
        translationKey: "astralDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xE6E6FA, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, emissive: 0xFFFFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xd0a1ff),
        attackCooldown: 0.5,
        attackEmmisiveIntensity: 4,
        minHealth: 8000,
        maxHealth: 12000
    },
    {
        name: "Kvantový drak",
        translationKey: "quantumDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, roughness: 0.1, metalness: 0.7, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, emissive: 0x2e7eff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x2e7eff),
        attackCooldown: 0.4,
        attackEmmisiveIntensity: 4,
        minHealth: 10000,
        maxHealth: 15000
    },
    {
        name: "Éterický drak",
        translationKey: "etherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffb5d8, emissive: 0xffb5d8, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffb5d8),
        attackCooldown: 0.3,
        attackEmmisiveIntensity: 4,
        minHealth: 12000,
        maxHealth: 18000
    },
    // Osmé podlaží
    {
        name: "Astrální drak",
        translationKey: "astralDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xE6E6FA, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, emissive: 0xFFFFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xd0a1ff),
        attackCooldown: 0.5,
        attackEmmisiveIntensity: 4,
        minHealth: 8000,
        maxHealth: 12000
    },
    {
        name: "Kvantový drak",
        translationKey: "quantumDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, roughness: 0.1, metalness: 0.7, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, emissive: 0x2e7eff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x2e7eff),
        attackCooldown: 0.4,
        attackEmmisiveIntensity: 4,
        minHealth: 10000,
        maxHealth: 15000
    },
    {
        name: "Éterický drak",
        translationKey: "etherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffb5d8, emissive: 0xffb5d8, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffb5d8),
        attackCooldown: 0.3,
        attackEmmisiveIntensity: 4,
        minHealth: 12000,
        maxHealth: 18000
    },
];