import * as THREE from 'three';

export const BOSS_TYPES = [
    // První podlaží
    {
        name: "Ohnivý drak",
        translationKey: "fireDragon",
        specialAttacks: ['multiShot', 'aoeBlast'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xff7542, roughness: 0.1, metalness: 0.1 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffa061, emissive: 0xffa061, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0xffa061),
        attackCooldown: 1,
        attackEmmisiveIntensity: 3,
        minHealth: 1000,
        maxHealth: 1500
    },
    {
        name: "Ledový drak",
        translationKey: "iceDragon",
        specialAttacks: ['frostbolt', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x45c1ff, roughness: 0.1, metalness: 0.1 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x5cf7ff, emissive: 0x5cf7ff, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x8af5ff),
        attackCooldown: 1,
        minHealth: 1500,
        maxHealth: 2000
    },
    {
        name: "Zemní drak",
        translationKey: "earthDragon",
        specialAttacks: ['aoeBlast', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x7bd672, roughness: 0.1, metalness: 0.1 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x5cff74, emissive: 0x5cff74, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x5cff74),
        attackCooldown: 1,
        minHealth: 1000,
        maxHealth: 2000
    },
    // Druhé podlaží
    {
        name: "Bouřkový drak",
        translationKey: "stormDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4169e1, roughness: 0.1, metalness: 0.3 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xecff6e, emissive: 0xecff6e, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x636eff),
        attackCooldown: 0.8,
        attackEmmisiveIntensity: 3,
        minHealth: 3000,
        maxHealth: 4500
    },
    {
        name: "Stínový drak",
        translationKey: "shadowDragon",
        specialAttacks: ['frostbolt', 'teleport', 'aoeBlast'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.2 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x8e4a91, emissive: 0x8e4a91, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x8e4a91),
        attackCooldown: 0.8,
        minHealth: 2500,
        maxHealth: 5000
    },
    {
        name: "Krystalový drak",
        translationKey: "crystalDragon",
        specialAttacks: ['multiShot', 'frostbolt', 'teleport'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x1fffff, emissive: 0x1fffff, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0x1fffff),
        attackCooldown: 0.8,
        minHealth: 3000,
        maxHealth: 6000
    },
    // Třetí podlaží
    {
        name: "Nebeský drak",
        translationKey: "celestialDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xadd8e6, roughness: 0.1, metalness: 0.5 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 2 }),
        attackColor: new THREE.Color(0xffffff),
        attackCooldown: 0.6,
        minHealth: 5500,
        maxHealth: 9000
    },
    {
        name: "Lávový drak",
        translationKey: "lavaDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8b0000, roughness: 0.1, metalness: 0.3 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff4500, emissive: 0xff4500, emissiveIntensity: 1.5 }),
        attackColor: new THREE.Color(0xff643d),
        attackEmmisiveIntensity: 3,
        attackCooldown: 0.6,
        minHealth: 8000,
        maxHealth: 11000
    },
    {
        name: "Vesmírný drak",
        translationKey: "spaceDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x3b278f, roughness: 0.1, metalness: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffd700, emissive: 0xffd700, emissiveIntensity: 5 }),
        attackColor: new THREE.Color(0xffe34d),
        attackEmmisiveIntensity: 5,
        attackCooldown: 0.6,
        minHealth: 6000,
        maxHealth: 12500
    },
    // Čtvrté podlaží
    {
        name: "Astrální drak",
        translationKey: "astralDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xE6E6FA, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, emissive: 0xFFFFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xd0a1ff),
        attackCooldown: 0.5,
        attackEmmisiveIntensity: 4,
        minHealth: 8000,
        maxHealth: 12000
    },
    {
        name: "Kvantový drak",
        translationKey: "quantumDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, roughness: 0.1, metalness: 0.7, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x2e7eff, emissive: 0x2e7eff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x2e7eff),
        attackCooldown: 0.4,
        attackEmmisiveIntensity: 4,
        minHealth: 10000,
        maxHealth: 15000
    },
    {
        name: "Éterický drak",
        translationKey: "etherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFFFF, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffb5d8, emissive: 0xffb5d8, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffb5d8),
        attackCooldown: 0.3,
        attackEmmisiveIntensity: 4,
        minHealth: 12000,
        maxHealth: 18000
    },
    // Páté podlaží (upravené parametry)
    {
        name: "Časový drak",
        translationKey: "timeDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xc0c0c0, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x00ffff, emissive: 0x00ffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x7fffff),
        attackCooldown: 0.6,
        attackSize: 0.3,
        attackDamage: 21,
        attackEmmisiveIntensity: 4,
        minHealth: 15000,
        maxHealth: 20000
    },
    {
        name: "Gravitační drak",
        translationKey: "gravityDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x9932cc, emissive: 0x9932cc, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xb870dc),
        attackCooldown: 0.588,
        attackSize: 0.29,
        attackDamage: 21,
        attackEmmisiveIntensity: 4,
        minHealth: 18000,
        maxHealth: 23000
    },
    {
        name: "Dimenzionální drak",
        translationKey: "dimensionalDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x00ced1, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff69b4, emissive: 0xff69b4, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xff69b4),
        attackCooldown: 0.576,
        attackSize: 0.28,
        attackDamage: 22,
        attackEmmisiveIntensity: 4,
        minHealth: 20000,
        maxHealth: 25000
    },
    // Šesté podlaží (upravené parametry)
    {
        name: "Toxický drak",
        translationKey: "toxicDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x32cd32, roughness: 0.1, metalness: 0.6 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xadff2f, emissive: 0xadff2f, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xadff2f),
        attackCooldown: 0.565,
        attackSize: 0.27,
        attackDamage: 23,
        attackEmmisiveIntensity: 4,
        minHealth: 22000,
        maxHealth: 28000
    },
    {
        name: "Plazmový drak",
        translationKey: "plasmaDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xff4500, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffa500, emissive: 0xffa500, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffa500),
        attackCooldown: 0.553,
        attackSize: 0.26,
        attackDamage: 24,
        attackEmmisiveIntensity: 4,
        minHealth: 25000,
        maxHealth: 30000
    },
    {
        name: "Magnetický drak",
        translationKey: "magneticDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4682b4, roughness: 0.1, metalness: 0.9 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x87cefa, emissive: 0x87cefa, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x87cefa),
        attackCooldown: 0.542,
        attackSize: 0.25,
        attackDamage: 26,
        attackEmmisiveIntensity: 4,
        minHealth: 28000,
        maxHealth: 33000
    },
    // Sedmé podlaží (upravené parametry)
    {
        name: "Polární drak",
        translationKey: "polarDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xf0f8ff, roughness: 0.1, metalness: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xe6e6fa, emissive: 0xe6e6fa, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xe6e6fa),
        attackCooldown: 0.530,
        attackSize: 0.24,
        attackDamage: 27,
        attackEmmisiveIntensity: 4,
        minHealth: 30000,
        maxHealth: 35000
    },
    {
        name: "Vulkanický drak",
        translationKey: "volcanicDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8b4513, roughness: 0.1, metalness: 0.6 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff6347, emissive: 0xff6347, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xff6347),
        attackCooldown: 0.519,
        attackSize: 0.23,
        attackDamage: 29,
        attackEmmisiveIntensity: 4,
        minHealth: 32000,
        maxHealth: 38000
    },
    {
        name: "Supravodivý drak",
        translationKey: "superconductiveDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4169e1, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x00ffff, emissive: 0x00ffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x7FFFFF),
        attackCooldown: 0.507,
        attackSize: 0.22,
        attackDamage: 30,
        attackEmmisiveIntensity: 4,
        minHealth: 35000,
        maxHealth: 40000
    },
    // Osmé podlaží (upravené parametry)
    {
        name: "Solární drak",
        translationKey: "solarDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xffd700, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff4500, emissive: 0xff4500, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xff4500),
        attackCooldown: 0.496,
        attackSize: 0.21,
        attackDamage: 32,
        attackEmmisiveIntensity: 4,
        minHealth: 38000,
        maxHealth: 43000
    },
    {
        name: "Lunární drak",
        translationKey: "lunarDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xc0c0c0, roughness: 0.1, metalness: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xe6e6fa, emissive: 0xe6e6fa, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xe6e6fa),
        attackCooldown: 0.484,
        attackSize: 0.20,
        attackDamage: 33,
        attackEmmisiveIntensity: 4,
        minHealth: 40000,
        maxHealth: 45000
    },
    {
        name: "Galaktický drak",
        translationKey: "galacticDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x9370db, emissive: 0x9370db, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x9370db),
        attackCooldown: 0.473,
        attackSize: 0.19,
        attackDamage: 34,
        attackEmmisiveIntensity: 4,
        minHealth: 42000,
        maxHealth: 48000
    },
    // Deváté podlaží (upravené parametry)
    {
        name: "Arkánní drak",
        translationKey: "arcaneDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8a2be2, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xee82ee, emissive: 0xee82ee, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xee82ee),
        attackCooldown: 0.461,
        attackSize: 0.18,
        attackDamage: 36,
        attackEmmisiveIntensity: 4,
        minHealth: 45000,
        maxHealth: 50000
    },
    {
        name: "Nekonečný drak",
        translationKey: "infinityDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x000000, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffffff),
        attackCooldown: 0.450,
        attackSize: 0.17,
        attackDamage: 38,
        attackEmmisiveIntensity: 4,
        minHealth: 48000,
        maxHealth: 53000
    },
    {
        name: "Vesmírný čas drak",
        translationKey: "spaceTimeDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x00ffff, emissive: 0x00ffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x7FFFFF),
        attackCooldown: 0.438,
        attackSize: 0.16,
        attackDamage: 40,
        attackEmmisiveIntensity: 4,
        minHealth: 50000,
        maxHealth: 55000
    },
    // Desáté podlaží (upravené parametry)
    {
        name: "Krvavý drak",
        translationKey: "bloodDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8b0000, roughness: 0.1, metalness: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff0000, emissive: 0xff0000, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xff0000),
        attackCooldown: 0.426,
        attackSize: 0.15,
        attackDamage: 41,
        attackEmmisiveIntensity: 4,
        minHealth: 52000,
        maxHealth: 58000
    },
    {
        name: "Temný éterický drak",
        translationKey: "darkEtherealDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x2f4f4f, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.7 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x7fffd4, emissive: 0x7fffd4, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x7fffd4),
        attackCooldown: 0.415,
        attackSize: 0.14,
        attackDamage: 43,
        attackEmmisiveIntensity: 4,
        minHealth: 55000,
        maxHealth: 60000
    },
    {
        name: "Kosmický drak",
        translationKey: "cosmicDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffd700, emissive: 0xffd700, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffd700),
        attackCooldown: 0.403,
        attackSize: 0.13,
        attackDamage: 45,
        attackEmmisiveIntensity: 4,
        minHealth: 58000,
        maxHealth: 63000
    },
    // Jedenácté podlaží (upravené parametry)
    {
        name: "Drak chaosu",
        translationKey: "chaosDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8b008b, roughness: 0.1, metalness: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff00ff, emissive: 0xff00ff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xff66ff),
        attackCooldown: 0.392,
        attackSize: 0.12,
        attackDamage: 47,
        attackEmmisiveIntensity: 4,
        minHealth: 60000,
        maxHealth: 65000
    },
    {
        name: "Drak rovnováhy",
        translationKey: "balanceDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x000000, emissive: 0x000000, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x808080),
        attackCooldown: 0.380,
        attackSize: 0.11,
        attackDamage: 49,
        attackEmmisiveIntensity: 4,
        minHealth: 62000,
        maxHealth: 68000
    },
    {
        name: "Drak věčnosti",
        translationKey: "eternityDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xffd700, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffffff),
        attackCooldown: 0.369,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 4,
        minHealth: 65000,
        maxHealth: 70000
    },
    // Dvanácté podlaží (upravené parametry)
    {
        name: "Drak stvoření",
        translationKey: "creationDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x00ff00, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffff00, emissive: 0xffff00, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffe456),
        attackCooldown: 0.357,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 4,
        minHealth: 68000,
        maxHealth: 73000
    },
    {
        name: "Drak zániku",
        translationKey: "destructionDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xff0000, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x000000, emissive: 0x000000, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x95bdac),
        attackCooldown: 0.346,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 4,
        minHealth: 70000,
        maxHealth: 75000
    },
    {
        name: "Drak vesmírné magie",
        translationKey: "cosmicMagicDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4b0082, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x00ffff, emissive: 0x00ffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x7FFFFF),
        attackCooldown: 0.334,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 4,
        minHealth: 73000,
        maxHealth: 78000
    },
    // Třinácté podlaží (upravené parametry)
    {
        name: "Drak prvotního ohně",
        translationKey: "primordialFireDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0xff4500, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffff00, emissive: 0xffff00, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffa147),
        attackCooldown: 0.323,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 4,
        minHealth: 75000,
        maxHealth: 80000
    },
    {
        name: "Drak prvotního ledu",
        translationKey: "primordialIceDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x00ffff, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xffffff),
        attackCooldown: 0.311,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 4,
        minHealth: 78000,
        maxHealth: 83000
    },
    {
        name: "Drak prvotní magie",
        translationKey: "primordialMagicDragon",
        specialAttacks: ['multiShot', 'aoeBlast', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x8a2be2, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xff00ff, emissive: 0xff00ff, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xa67bff),
        attackCooldown: 0.3,
        attackSize: 0.10,
        attackDamage: 50,
        attackEmmisiveIntensity: 5,
        minHealth: 80000,
        maxHealth: 85000
    },      // Třinácté podlaží (upravené parametry)
    {
        name: "Drak noční oblohy",
        translationKey: "nightSkyDragon",
        specialAttacks: ['multiShot','teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x191970, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xFFFF00, emissive: 0xFFFF00, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x4169E1),
        attackCooldown: 0.8,
        attackSpeed: 0.5,
        attackSize: 0.2,
        attackDamage: 60,
        attackEmmisiveIntensity: 5,
        minHealth: 30000,
        maxHealth: 30000
    },
    {
        name: "Drak hlubinného ledu",
        translationKey: "abyssalIceDragon",
        specialAttacks: ['multiShot', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x4682B4, roughness: 0.2, metalness: 0.8, transparent: true, opacity: 0.85 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0xE0FFFF, emissive: 0xE0FFFF, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0xAFEEEE),
        attackCooldown: 1,
        attackSpeed: 0.7,
        attackSize: 0.2,
        attackDamage: 60,
        attackEmmisiveIntensity: 4,
        minHealth: 30000,
        maxHealth: 30000
    },
    {
        name: "Drak oceánské magie",
        translationKey: "oceanicMagicDragon",
        specialAttacks: ['multiShot', 'teleport', 'frostbolt', 'magicArrow'],
        dragonMainMaterial: new THREE.MeshStandardMaterial({ color: 0x000080, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.8 }),
        eyeBlackMaterial: new THREE.MeshStandardMaterial({ color: 0x000000 }),
        eyeWhiteMaterial: new THREE.MeshStandardMaterial({ color: 0x7B68EE, emissive: 0x7B68EE, emissiveIntensity: 3 }),
        attackColor: new THREE.Color(0x1E90FF),
        attackCooldown: 0.8,
        attackSpeed: 0.6,
        attackSize: 0.2,
        attackDamage: 60,
        attackEmmisiveIntensity: 5,
        minHealth: 30000,
        maxHealth: 30000
    }
];