// Konstanty pro typy předmětů
export const ITEM_TYPES = {
    WEAPON: 'weapon',
    ARMOR: 'armor',
    HP_POTION: 'hpPotion',
    MP_POTION: 'mpPotion'
  };
  
  // Konstanty pro vzácnosti předmětů
  export const ITEM_RARITIES = {
    COMMON: 'common',
    UNCOMMON: 'uncommon',
    RARE: 'rare',
    EPIC: 'epic',
    LEGENDARY: 'legendary',
    MYTHIC: 'mythic'
  };

  export function getItemName(item) {
    for (let [klic, val] of Object.entries(itemDatabase)) {
        if (val === item) {
          return klic;
        }
      }
      return null;  // Pokud nenajde žádnou shodu
    }

export const itemDatabase = {
  healthPotion: {
    name: "Health Potion",
    type: ITEM_TYPES.HP_POTION,
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: true,
    sellPrice: 5,
    buyPrice: 10,
    stackable: true,
    icon: 'inventory/hp-slot.jpg',
    restoreAmount: 50,
    description: "Restores 50 health."
  },
  manaPotion: {
    name: "Mana Potion",
    type: ITEM_TYPES.MP_POTION,
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: true,
    sellPrice: 5,
    buyPrice: 10,
    stackable: true,
    icon: 'inventory/mp-slot.jpg',
    restoreAmount: 50,
    description: "Restores 50 mana."
  },
  greaterHealthPotion: {
    name: "Greater Health Potion",
    type: ITEM_TYPES.HP_POTION,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 10,
    sellable: true,
    sellPrice: 20,
    buyPrice: 40,
    stackable: true,
    icon: 'inventory/potions/greater-health-potion.jpg',
    restoreAmount: 100,
    description: "Restores 100 health."
  },
  greaterManaPotion: {
    name: "Greater Mana Potion",
    type: ITEM_TYPES.MP_POTION,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 10,
    sellable: true,
    sellPrice: 20,
    buyPrice: 40,
    stackable: true,
    icon: 'inventory/potions/greater-mana-potion.jpg',
    restoreAmount: 100,
    description: "Restores 100 mana."
  },
  ultimateHealthPotion: {
    name: "Ultimate Health Potion",
    type: ITEM_TYPES.HP_POTION,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 20,
    sellable: true,
    sellPrice: 100,
    buyPrice: 200,
    stackable: true,
    icon: 'inventory/potions/ultimate-health-potion.jpg',
    restoreAmount: "75%",
    description: "Restores 75% of your health."
  },
  ultimateManaPotion: {
    name: "Ultimate Mana Potion",
    type: ITEM_TYPES.MP_POTION,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 20,
    sellable: true,
    sellPrice: 100,
    buyPrice: 200,
    stackable: true,
    icon: 'inventory/potions/ultimate-mana-potion.jpg',
    restoreAmount: "75%",
    description: "Restores 75% of your mana."
  },
  angelsGraceVestments: {
    name: "Angel's Grace Vestments",
    type: "armor",
    rarity: "legendary",
    requiredLevel: 55,
    sellable: true,
    sellPrice: 5000,
    buyPrice: 15000,
    stackable: false,
    icon: 'inventory/armor/angels-grace-vestments.jpg',
    hpBonus: 150,
    mpBonus: 200,
    description: "Blessed by celestial beings, these vestments grant divine protection and immense magical power."
  },
  arcaneRunecloak: {
    name: "Arcane Runecloak",
    type: "armor",
    rarity: "epic",
    requiredLevel: 45,
    sellable: true,
    sellPrice: 3000,
    buyPrice: 9000,
    stackable: false,
    icon: 'inventory/armor/arcane-runecloak.jpg',
    hpBonus: 100,
    mpBonus: 150,
    description: "Inscribed with ancient runes, this cloak enhances magical abilities and provides substantial protection."
  },
  bloomShadeKimono: {
    name: "Bloom Shade Kimono",
    type: "armor",
    rarity: "rare",
    requiredLevel: 35,
    sellable: true,
    sellPrice: 1500,
    buyPrice: 4500,
    stackable: false,
    icon: 'inventory/armor/bloom-shade-kimono.jpg',
    hpBonus: 80,
    mpBonus: 100,
    description: "A beautiful kimono that blends nature's beauty with shadowy protection."
  },
  crimsonEmberCloak: {
    name: "Crimson Ember Cloak",
    type: "armor",
    rarity: "epic",
    requiredLevel: 50,
    sellable: true,
    sellPrice: 3500,
    buyPrice: 10500,
    stackable: false,
    icon: 'inventory/armor/crimson-ember-cloak.jpg',
    hpBonus: 120,
    mpBonus: 130,
    description: "Imbued with the essence of fire, this cloak offers formidable protection and enhances fire-based spells."
  },
  emeraldSagesAttire: {
    name: "Emerald Sage's Attire",
    type: "armor",
    rarity: "epic",
    requiredLevel: 40,
    sellable: true,
    sellPrice: 2800,
    buyPrice: 8400,
    stackable: false,
    icon: 'inventory/armor/emerald-sages-attire.jpg',
    hpBonus: 90,
    mpBonus: 140,
    description: "Worn by the wisest of nature mages, this attire grants deep connection to natural energies."
  },
  flamewreathedMantle: {
    name: "Flamewreathed Mantle",
    type: "armor",
    rarity: "rare",
    requiredLevel: 30,
    sellable: true,
    sellPrice: 1200,
    buyPrice: 3600,
    stackable: false,
    icon: 'inventory/armor/flamewreathed-mantle.jpg',
    hpBonus: 70,
    mpBonus: 90,
    description: "A mantle surrounded by magical flames, offering protection against fire and cold."
  },
  goldenDawnRobe: {
    name: "Golden Dawn Robe",
    type: "armor",
    rarity: "epic",
    requiredLevel: 45,
    sellable: true,
    sellPrice: 3200,
    buyPrice: 9600,
    stackable: false,
    icon: 'inventory/armor/golden-dawn-robe.jpg',
    hpBonus: 110,
    mpBonus: 120,
    description: "Radiating with the power of the sun, this robe enhances light-based magic and provides excellent protection."
  },
  infernalDragonhideRobe: {
    name: "Infernal Dragonhide Robe",
    type: "armor",
    rarity: "legendary",
    requiredLevel: 60,
    sellable: true,
    sellPrice: 6000,
    buyPrice: 18000,
    stackable: false,
    icon: 'inventory/armor/infernal-dragonhide-robe.jpg',
    hpBonus: 180,
    mpBonus: 160,
    description: "Crafted from the hide of an infernal dragon, this robe offers unparalleled protection and boosts fire magic."
  },
  novicesFrostedMantle: {
    name: "Novice's Frosted Mantle",
    type: "armor",
    rarity: "common",
    requiredLevel: 1,
    sellable: true,
    sellPrice: 50,
    buyPrice: 150,
    stackable: false,
    icon: 'inventory/armor/novices-frosted-mantle.jpg',
    hpBonus: 20,
    mpBonus: 30,
    description: "A simple mantle enchanted with frost magic, perfect for novice ice mages."
  },
  phoenixFlameRobe: {
    name: "Phoenix Flame Robe",
    type: "armor",
    rarity: "epic",
    requiredLevel: 50,
    sellable: true,
    sellPrice: 3800,
    buyPrice: 11400,
    stackable: false,
    icon: 'inventory/armor/phoenix-flame-robe.jpg',
    hpBonus: 130,
    mpBonus: 140,
    description: "Infused with the essence of a phoenix, this robe grants fire resistance and enhances resurrection spells."
  },
  starlightSurgeRobe: {
    name: "Starlight Surge Robe",
    type: "armor",
    rarity: "rare",
    requiredLevel: 25,
    sellable: true,
    sellPrice: 1000,
    buyPrice: 3000,
    stackable: false,
    icon: 'inventory/armor/starlight-surge-robe.jpg',
    hpBonus: 60,
    mpBonus: 80,
    description: "Imbued with celestial energy, this robe enhances astral and light-based spells."
  },
  stormcallersAegis: {
    name: "Stormcaller's Aegis",
    type: "armor",
    rarity: "epic",
    requiredLevel: 55,
    sellable: true,
    sellPrice: 4000,
    buyPrice: 12000,
    stackable: false,
    icon: 'inventory/armor/stormcallers-aegis.jpg',
    hpBonus: 140,
    mpBonus: 150,
    description: "Worn by master storm mages, this aegis grants control over lightning and provides excellent magical defense."
  },
  voidwalkersShroud: {
    name: "Voidwalker's Shroud",
    type: "armor",
    rarity: "mythic",
    requiredLevel: 60,
    sellable: true,
    sellPrice: 8000,
    buyPrice: 24000,
    stackable: false,
    icon: 'inventory/armor/voidwalkers-shroud.jpg',
    hpBonus: 200,
    mpBonus: 250,
    description: "A mysterious shroud that allows the wearer to tap into the power of the void, granting immense magical abilities."
  },
  angelsFeatherOfGrace: {
    name: "Angel's Feather of Grace",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 55,
    sellable: true,
    sellPrice: 5000,
    buyPrice: 15000,
    stackable: false,
    icon: 'inventory/staff/angels-feather-of-grace.jpg',
    attackBonus: 150,
    hpBonus: 100,
    mpBonus: 200,
    description: "A staff created from an archangel's feather, granting its wielder divine power and grace."
  },
  apprenticeShardStaff: {
    name: "Apprentice Shard Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: false,
    sellPrice: 10,
    buyPrice: 30,
    stackable: false,
    icon: 'inventory/staff/apprentice-shard-staff.jpg',
    description: "A simple staff for novice mages, crafted from a magical crystal shard."
  },
  celestialLightbringer: {
    name: "Celestial Lightbringer",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 45,
    sellable: true,
    sellPrice: 3000,
    buyPrice: 9000,
    stackable: false,
    icon: 'inventory/staff/celestial-lightbringer.jpg',
    attackBonus: 100,
    mpBonus: 150,
    description: "A staff imbued with the power of celestial bodies, illuminating the path and empowering light magic."
  },
  darkshadeStaff: {
    name: "Darkshade Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 30,
    sellable: true,
    sellPrice: 1200,
    buyPrice: 3600,
    stackable: false,
    icon: 'inventory/staff/darkshade-scepter.jpg',
    attackBonus: 70,
    mpBonus: 80,
    description: "A staff that harnesses the power of shadows, ideal for practitioners of dark magic."
  },
  druidsWhisperwood: {
    name: "Druid's Whisperwood",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 25,
    sellable: true,
    sellPrice: 1000,
    buyPrice: 3000,
    stackable: false,
    icon: 'inventory/staff/druids-whisperwood.jpg',
    attackBonus: 60,
    hpBonus: 50,
    mpBonus: 50,
    description: "A staff carved from ancient whisperwood, resonating with nature's power."
  },
  emeraldVineStaff: {
    name: "Emerald Vine Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 15,
    sellable: true,
    sellPrice: 500,
    buyPrice: 1500,
    stackable: false,
    icon: 'inventory/staff/emerald-vine-staff.jpg',
    attackBonus: 30,
    hpBonus: 30,
    description: "A staff entwined with living emerald vines, channeling the essence of growth and vitality."
  },
  flamebindersWrath: {
    name: "Flamebinder's Wrath",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 50,
    sellable: true,
    sellPrice: 3500,
    buyPrice: 10500,
    stackable: false,
    icon: 'inventory/staff/flamebinders-wrath.jpg',
    attackBonus: 120,
    mpBonus: 100,
    description: "A staff that burns with the fury of ancient fire elementals, devastating in combat."
  },
  frostbaneCorruption: {
    name: "Frostbane Corruption",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 40,
    sellable: true,
    sellPrice: 2800,
    buyPrice: 8400,
    stackable: false,
    icon: 'inventory/staff/frostbane-corruption.jpg',
    attackBonus: 90,
    mpBonus: 120,
    description: "A staff tainted by frost magic gone awry, powerful but with a hint of corruption."
  },
  infernalDragonflare: {
    name: "Infernal Dragonflare",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 60,
    sellable: true,
    sellPrice: 6000,
    buyPrice: 18000,
    stackable: false,
    icon: 'inventory/staff/infernal-dragonflare.jpg',
    attackBonus: 180,
    hpBonus: 150,
    mpBonus: 150,
    description: "A staff forged in dragon fire, containing the essence of an ancient infernal wyrm."
  },
  venomskullStaff: {
    name: "Venomskull Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 35,
    sellable: true,
    sellPrice: 1500,
    buyPrice: 4500,
    stackable: false,
    icon: 'inventory/staff/venomskull-staff.jpg',
    attackBonus: 80,
    mpBonus: 90,
    description: "A staff topped with a venomous skull, perfect for casting poison and curse spells."
  }
};