import { staffModelsDefinitons } from './staffModels.js';


// Konstanty pro typy předmětů
export const ITEM_TYPES = {
    WEAPON: 'weapon',
    ARMOR: 'armor',
    HP_POTION: 'hpPotion',
    MP_POTION: 'mpPotion'
  };
  
  // Konstanty pro vzácnosti předmětů
  export const ITEM_RARITIES = {
    COMMON: 'common',
    UNCOMMON: 'uncommon',
    RARE: 'rare',
    EPIC: 'epic',
    LEGENDARY: 'legendary',
    MYTHIC: 'mythic'
  };

  export function getItemName(item) {
    for (let [klic, val] of Object.entries(itemDatabase)) {
        if (val === item) {
          return klic;
        }
      }
      return null;  // Pokud nenajde žádnou shodu
    }


export const itemDatabase = {
  healthPotion: {
    name: "Health Potion",
    type: ITEM_TYPES.HP_POTION,
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: true,
    sellPrice: 5,
    buyPrice: 10,
    stackable: true,
    icon: 'inventory/hp-slot.jpg',
    restoreAmount: 50,
    description: "Restores 50 health."
  },
  manaPotion: {
    name: "Mana Potion",
    type: ITEM_TYPES.MP_POTION,
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: true,
    sellPrice: 5,
    buyPrice: 10,
    stackable: true,
    icon: 'inventory/mp-slot.jpg',
    restoreAmount: 50,
    description: "Restores 50 mana."
  },
  greaterHealthPotion: {
    name: "Greater Health Potion",
    type: ITEM_TYPES.HP_POTION,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 10,
    sellable: true,
    sellPrice: 20,
    buyPrice: 40,
    stackable: true,
    icon: 'inventory/potions/greater-health-potion.jpg',
    restoreAmount: 100,
    description: "Restores 100 health."
  },
  greaterManaPotion: {
    name: "Greater Mana Potion",
    type: ITEM_TYPES.MP_POTION,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 10,
    sellable: true,
    sellPrice: 20,
    buyPrice: 40,
    stackable: true,
    icon: 'inventory/potions/greater-mana-potion.jpg',
    restoreAmount: 100,
    description: "Restores 100 mana."
  },
  ultimateHealthPotion: {
    name: "Ultimate Health Potion",
    type: ITEM_TYPES.HP_POTION,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 20,
    sellable: true,
    sellPrice: 100,
    buyPrice: 200,
    stackable: true,
    icon: 'inventory/potions/ultimate-health-potion.jpg',
    restoreAmount: "75%",
    description: "Restores 75% of your health."
  },
  ultimateManaPotion: {
    name: "Ultimate Mana Potion",
    type: ITEM_TYPES.MP_POTION,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 20,
    sellable: true,
    sellPrice: 100,
    buyPrice: 200,
    stackable: true,
    icon: 'inventory/potions/ultimate-mana-potion.jpg',
    restoreAmount: "75%",
    description: "Restores 75% of your mana."
  },
  angelsGraceVestments: {
    name: "Angel's Grace Vestments",
    type: "armor",
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 55,
    sellable: true,
    sellPrice: 5000,
    buyPrice: 15000,
    stackable: false,
    icon: 'inventory/armor/angels-grace-vestments.jpg',
    hpBonus: 150,
    mpBonus: 200,
    description: "Blessed by celestial beings, these vestments grant divine protection and immense magical power.",
    playerPreview: 'inventory/player/angels-grace-vestments-preview.jpg',
  },
  arcaneRunecloak: {
    name: "Arcane Runecloak",
    type: "armor",
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 25,
    sellable: true,
    sellPrice: 1000,
    buyPrice: 3000,
    stackable: false,
    icon: 'inventory/armor/arcane-runecloak.jpg',
    hpBonus: 60,
    mpBonus: 80,
    description: "Inscribed with ancient runes, this cloak enhances magical abilities and provides substantial protection.",
    playerPreview: 'inventory/player/arcane-runecloak-preview.jpg',
  },
  bloomShadeKimono: {
    name: "Bloom Shade Kimono",
    type: "armor",
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 30,
    sellable: true,
    sellPrice: 1200,
    buyPrice: 3600,
    stackable: false,
    icon: 'inventory/armor/bloom-shade-kimono.jpg',
    hpBonus: 70,
    mpBonus: 90,
    description: "A beautiful kimono that blends nature's beauty with shadowy protection.",
    playerPreview: 'inventory/player/bloom-shade-kimono-preview.jpg',
  },
  crimsonEmberCloak: {
    name: "Crimson Ember Cloak",
    type: "armor",
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 50,
    sellable: true,
    sellPrice: 500,
    buyPrice: 1500,
    stackable: false,
    icon: 'inventory/armor/crimson-ember-cloak.jpg',
    hpBonus: 50,
    mpBonus: 60,
    description: "Imbued with the essence of fire, this cloak offers basic protection and slightly enhances fire-based spells.",
    playerPreview: 'inventory/player/crimson-ember-cloak-preview.jpg',
  },
  emeraldSagesAttire: {
    name: "Emerald Sage's Attire",
    type: "armor",
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 40,
    sellable: true,
    sellPrice: 2800,
    buyPrice: 8400,
    stackable: false,
    icon: 'inventory/armor/emerald-sages-attire.jpg',
    hpBonus: 90,
    mpBonus: 140,
    description: "Worn by the wisest of nature mages, this attire grants deep connection to natural energies.",
    playerPreview: 'inventory/player/emerald-sages-attire-preview.jpg',
  },
  flamewreathedMantle: {
    name: "Flamewreathed Mantle",
    type: "armor",
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 35,
    sellable: true,
    sellPrice: 3500,
    buyPrice: 10500,
    stackable: false,
    icon: 'inventory/armor/flamewreathed-mantle.jpg',
    hpBonus: 150,
    mpBonus: 180,
    description: "A legendary mantle surrounded by magical flames, offering exceptional protection against fire and cold.",
    playerPreview: 'inventory/player/flamewreathed-mantle-preview.jpg',
  },
  goldenDawnRobe: {
    name: "Golden Dawn Robe",
    type: "armor",
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 30,
    sellable: true,
    sellPrice: 300,
    buyPrice: 900,
    stackable: false,
    icon: 'inventory/armor/golden-dawn-robe.jpg',
    hpBonus: 30,
    mpBonus: 40,
    description: "A simple robe with a golden hue, providing basic protection and a slight boost to light-based magic.",
    playerPreview: 'inventory/player/golden-dawn-robe-preview.jpg',
  },
  infernalDragonhideRobe: {
    name: "Infernal Dragonhide Robe",
    type: "armor",
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 60,
    sellable: true,
    sellPrice: 6000,
    buyPrice: 18000,
    stackable: false,
    icon: 'inventory/armor/infernal-dragonhide-robe.jpg',
    hpBonus: 180,
    mpBonus: 160,
    description: "Crafted from the hide of an infernal dragon, this robe offers unparalleled protection and boosts fire magic.",
    playerPreview: 'inventory/player/infernal-dragonhide-robe-preview.jpg',
  },
  novicesFrostedMantle: {
    name: "Novice's Frosted Mantle",
    type: "armor",
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: true,
    sellPrice: 50,
    buyPrice: 150,
    stackable: false,
    icon: 'inventory/armor/novices-frosted-mantle.jpg',
    hpBonus: 20,
    mpBonus: 30,
    description: "A simple mantle enchanted with frost magic, perfect for novice ice mages.",
    playerPreview: 'inventory/player/novices-frosted-mantle-preview.jpg',
  },
  phoenixFlameRobe: {
    name: "Phoenix Flame Robe",
    type: "armor",
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 50,
    sellable: true,
    sellPrice: 2000,
    buyPrice: 6000,
    stackable: false,
    icon: 'inventory/armor/phoenix-flame-robe.jpg',
    hpBonus: 100,
    mpBonus: 120,
    description: "Infused with the essence of a phoenix, this robe grants fire resistance and enhances resurrection spells.",
    playerPreview: 'inventory/player/phoenix-flame-robe-preview.jpg',
  },
  starlightSurgeRobe: {
    name: "Starlight Surge Robe",
    type: "armor",
    rarity: ITEM_RARITIES.MYTHIC,
    requiredLevel: 35,
    sellable: true,
    sellPrice: 5000,
    buyPrice: 15000,
    stackable: false,
    icon: 'inventory/armor/starlight-surge-robe.jpg',
    hpBonus: 180,
    mpBonus: 220,
    description: "Imbued with celestial energy, this mythical robe greatly enhances astral and light-based spells.",
    playerPreview: 'inventory/player/starlight-surge-robe-preview.jpg',
  },
  stormcallersAegis: {
    name: "Stormcaller's Aegis",
    type: "armor",
    rarity: "epic",
    requiredLevel: 55,
    sellable: true,
    sellPrice: 4000,
    buyPrice: 12000,
    stackable: false,
    icon: 'inventory/armor/stormcallers-aegis.jpg',
    hpBonus: 140,
    mpBonus: 150,
    description: "Worn by master storm mages, this aegis grants control over lightning and provides excellent magical defense.",
    playerPreview: 'inventory/player/stormcallers-aegis-preview.jpg',
  },
  voidwalkersShroud: {
    name: "Voidwalker's Shroud",
    type: "armor",
    rarity: "mythic",
    requiredLevel: 60,
    sellable: true,
    sellPrice: 8000,
    buyPrice: 24000,
    stackable: false,
    icon: 'inventory/armor/voidwalkers-shroud.jpg',
    hpBonus: 200,
    mpBonus: 250,
    description: "A mysterious shroud that allows the wearer to tap into the power of the void, granting immense magical abilities.",
    playerPreview: 'inventory/player/voidwalkers-shroud-preview.jpg',
  },
  scarletRunecLoak: {
    name: "Scarlet RunecLoak",
    type: ITEM_TYPES.ARMOR,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 15,
    sellable: true,
    sellPrice: 300,
    buyPrice: 900,
    stackable: false,
    icon: 'inventory/armor/scarlet-runecLoak.jpg',
    hpBonus: 40,
    mpBonus: 50,
    description: "A cloak inscribed with basic runes, slightly enhancing fire-based spells and providing moderate protection.",
    playerPreview: 'inventory/player/scarlet-runecLoak-preview.jpg',
  },
  cloudweaversMantle: {
    name: "Cloudweaver's Mantle",
    type: ITEM_TYPES.ARMOR,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 40,
    sellable: true,
    sellPrice: 2500,
    buyPrice: 7500,
    stackable: false,
    icon: 'inventory/armor/cloudweavers-mantle.jpg',
    hpBonus: 100,
    mpBonus: 120,
    description: "A mantle woven from clouds, granting the wearer agility and enhanced air-based magic.",
    playerPreview: 'inventory/player/cloudweavers-mantle-preview.jpg',
  },
  obsidianGlyphcloak: {
    name: "Obsidian Glyphcloak",
    type: ITEM_TYPES.ARMOR,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 45,
    sellable: true,
    sellPrice: 900,
    buyPrice: 2700,
    stackable: false,
    icon: 'inventory/armor/obsidian-glyphcloak.jpg',
    hpBonus: 70,
    mpBonus: 80,
    description: "A cloak adorned with obsidian glyphs, providing good protection and slightly boosting dark magic.",
    playerPreview: 'inventory/player/obsidian-glyphcloak-preview.jpg',
  },
  guardiansSkyshroud: {
    name: "Guardian's Skyshroud",
    type: ITEM_TYPES.ARMOR,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 55,
    sellable: true,
    sellPrice: 1100,
    buyPrice: 3300,
    stackable: false,
    icon: 'inventory/armor/guardians-skyshroud.jpg',
    hpBonus: 90,
    mpBonus: 100,
    description: "A shroud worn by the guardians of the sky, offering good protection and slightly enhancing wind-based magic.",
    playerPreview: 'inventory/player/guardians-skyshroud-preview.jpg',
  },
  sunflareRobe: {
    name: "Sunflare Robe",
    type: ITEM_TYPES.ARMOR,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 35,
    sellable: true,
    sellPrice: 1500,
    buyPrice: 4500,
    stackable: false,
    icon: 'inventory/armor/sunflare-robe.jpg',
    hpBonus: 80,
    mpBonus: 100,
    description: "A robe that radiates with the power of the sun, granting enhanced magical abilities and protection.",
    playerPreview: 'inventory/player/sunflare-robe-preview.jpg',
  },
  angelsFeatherOfGrace: {
    name: "Angel's Feather of Grace",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 55,
    sellable: true,
    sellPrice: 5000,
    buyPrice: 15000,
    stackable: false,
    icon: 'inventory/staff/angels-feather-of-grace.jpg',
    attackBonus: 150,
    hpBonus: 100,
    mpBonus: 200,
    description: "A staff created from an archangel's feather, granting its wielder divine power and grace.",
    modelInfo: staffModelsDefinitons.angelsFeatherOfGrace
  },
  apprenticeShardStaff: {
    name: "Apprentice Shard Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.COMMON,
    requiredLevel: 1,
    sellable: false,
    sellPrice: 10,
    buyPrice: 30,
    stackable: false,
    icon: 'inventory/staff/apprentice-shard-staff.jpg',
    description: "A simple staff for novice mages, crafted from a magical crystal shard.",
    modelInfo: staffModelsDefinitons.apprenticeShardStaff
  },
  celestialLightbringer: {
    name: "Celestial Lightbringer",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 45,
    sellable: true,
    sellPrice: 3000,
    buyPrice: 9000,
    stackable: false,
    icon: 'inventory/staff/celestial-lightbringer.jpg',
    attackBonus: 100,
    mpBonus: 150,
    description: "A staff imbued with the power of celestial bodies, illuminating the path and empowering light magic.",
    modelInfo: staffModelsDefinitons.apprenticeShardStaff
  },
  darkshadeStaff: {
    name: "Darkshade Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 30,
    sellable: true,
    sellPrice: 1200,
    buyPrice: 3600,
    stackable: false,
    icon: 'inventory/staff/darkshade-scepter.jpg',
    attackBonus: 70,
    mpBonus: 80,
    description: "A staff that harnesses the power of shadows, ideal for practitioners of dark magic.",
    modelInfo: staffModelsDefinitons.apprenticeShardStaff
  },
  druidsWhisperwood: {
    name: "Druid's Whisperwood",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 25,
    sellable: true,
    sellPrice: 1000,
    buyPrice: 3000,
    stackable: false,
    icon: 'inventory/staff/druids-whisperwood.jpg',
    attackBonus: 60,
    hpBonus: 50,
    mpBonus: 50,
    description: "A staff carved from ancient whisperwood, resonating with nature's power.",
    modelInfo: staffModelsDefinitons.druidsWhisperwood
  },
  emeraldVineStaff: {
    name: "Emerald Vine Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.UNCOMMON,
    requiredLevel: 15,
    sellable: true,
    sellPrice: 500,
    buyPrice: 1500,
    stackable: false,
    icon: 'inventory/staff/emerald-vine-staff.jpg',
    attackBonus: 30,
    hpBonus: 30,
    description: "A staff entwined with living emerald vines, channeling the essence of growth and vitality.",
    modelInfo: staffModelsDefinitons.apprenticeShardStaff
  },
  flamebindersWrath: {
    name: "Flamebinder's Wrath",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 50,
    sellable: true,
    sellPrice: 3500,
    buyPrice: 10500,
    stackable: false,
    icon: 'inventory/staff/flamebinders-wrath.jpg',
    attackBonus: 120,
    mpBonus: 100,
    description: "A staff that burns with the fury of ancient fire elementals, devastating in combat.",
    modelInfo: staffModelsDefinitons.apprenticeShardStaff
  },
  frostbaneCorruption: {
    name: "Frostbane Corruption",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.EPIC,
    requiredLevel: 40,
    sellable: true,
    sellPrice: 2800,
    buyPrice: 8400,
    stackable: false,
    icon: 'inventory/staff/frostbane-corruption.jpg',
    attackBonus: 90,
    mpBonus: 120,
    description: "A staff tainted by frost magic gone awry, powerful but with a hint of corruption.",
    modelInfo: staffModelsDefinitons.apprenticeShardStaff
  },
  infernalDragonflare: {
    name: "Infernal Dragonflare",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.LEGENDARY,
    requiredLevel: 60,
    sellable: true,
    sellPrice: 6000,
    buyPrice: 18000,
    stackable: false,
    icon: 'inventory/staff/infernal-dragonflare.jpg',
    attackBonus: 180,
    hpBonus: 150,
    mpBonus: 150,
    description: "A staff forged in dragon fire, containing the essence of an ancient infernal wyrm.",
    modelInfo: staffModelsDefinitons.infernalDragonflare
  },
  venomskullStaff: {
    name: "Venomskull Staff",
    type: ITEM_TYPES.WEAPON,
    rarity: ITEM_RARITIES.RARE,
    requiredLevel: 35,
    sellable: true,
    sellPrice: 1500,
    buyPrice: 4500,
    stackable: false,
    icon: 'inventory/staff/venomskull-staff.jpg',
    attackBonus: 80,
    mpBonus: 90,
    description: "A staff topped with a venomous skull, perfect for casting poison and curse spells.",
    modelInfo: staffModelsDefinitons.venomskullStaff  
  }
};

export function getDefaultPlayerPreview() {
  return 'inventory/player/default-preview.jpg';
}