import { FilmPass } from "three/examples/jsm/Addons.js";

//angels-feather-of-grace
export const staffModelsDefinitons = {
  staff: {
    modelPath: "models/staffs/Staff.glb",
    scale1: 0.1,
    scale2: 0.1,
    scale3: 0.1,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: Math.PI / 2,
    rotationZ: 0,
  },
  angelsFeatherOfGrace: {
    modelPath: "models/staffs/angels-feather-of-grace.glb",
    scaleX: 0.8,
    scaleY: 0.8,
    scaleZ: 0.8,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: Math.PI / 2,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  infernalDragonflare: {
    modelPath: "models/staffs/infernal-dragonflare.glb",
    scaleX: 0.65,
    scaleY: 0.65,
    scaleZ: 0.65,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: -0.5,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  venomskullStaff: {
    modelPath: "models/staffs/venomskull-staff.glb",
    scaleX: 0.65,
    scaleY: 0.65,
    scaleZ: 0.65,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0.1,
    rotationY: -0.6,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  darkshadeStaff: {
    modelPath: "models/staffs/darkshade-scepter.glb",
    scaleX: 0.62,
    scaleY: 0.62,
    scaleZ: 0.62,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: 1.8,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  emeraldVineStaff: {
    modelPath: "models/staffs/emerald-vine-staff.glb",
    scaleX: 0.62,
    scaleY: 0.62,
    scaleZ: 0.62,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: -0.5,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  celestialLightbringer: {
    modelPath: "models/staffs/celestial-lightbringer.glb",
    scaleX: 0.50,
    scaleY: 0.50,
    scaleZ: 0.50,
    positionX: 0.3,
    positionY: -0.04,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: -3.3,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  flamebindersWrath: {
    modelPath: "models/staffs/flamebinders-wrath.glb",
    scaleX: 0.50,
    scaleY: 0.50,
    scaleZ: 0.50,
    positionX: 0.3,
    positionY: -0.08,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    castEffectOffsetY: 0.5,
  },
  frostbaneCorruption: {
    modelPath: "models/staffs/frostbane-corruption.glb",
    scaleX: 0.60,
    scaleY: 0.60,
    scaleZ: 0.60,
    positionX: 0.3,
    positionY: -0.12,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    castEffectOffsetY: 0.3,
  },
  druidsWhisperwood: {
    modelPath: "models/staffs/druids-whisperwood.glb",
    scaleX: 0.58,
    scaleY: 0.58,
    scaleZ: 0.58,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: -1.5,
    rotationZ: 0,
    castEffectOffsetY: 0.4,
  },
  apprenticeShardStaff: {
    modelPath: "models/staffs/apprentice-shard-staff.glb",
    scaleX: 0.75,
    scaleY: 0.75,
    scaleZ: 0.75,
    positionX: 0.3,
    positionY: -0.2,
    positionZ: -0.5,
    rotationX: 0,
    rotationY: Math.PI / 2,
    rotationZ: 0,
    emissivePartName:"Piedra_arriba_low_piedra_brilli_brilli_0",
    castEffectOffsetY: 0.5,
  },
};
